---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        name: Check trailing whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: Check yaml files (yamllint)
  - repo: https://github.com/fauust/pre-commit-shell
    rev: v1.1
    hooks:
      - id: shellcheck
        name: Check shell script (shellcheck)
        args: ["-x"]
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        name: Check for markdown lint (mdl)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        name: Checks for common misspellings in text files
        entry: codespell
        language: python
  - repo: local
    hooks:
    #   - id: docker-prettier
    #     name: Run prettier with docker
    #     entry: tmknom/prettier:latest -l
    #     language: docker_image
    #     files: "\\.(\
    #       css|less|scss\
    #       |graphql|gql\
    #       |html\
    #       |js|jsx\
    #       |json\
    #       |md|markdown|mdown|mkdn\
    #       |mdx\
    #       |ts|tsx\
    #       |vue\
    #       |yaml|yml\
    #       )$"
      - id: docker-lychee
        name: Run lychee on markdown files with docker
        entry: lycheeverse/lychee
        language: docker_image
        types: [markdown]
